---

- name: Install fish
  community.general.homebrew:
    name:
      - fish
      - fisher

- name: Link fish dotfiles
  file:
    state: link
    src: "../../{{ playbook_dir | replace(lookup('env', 'HOME') + '/', '') }}/roles/fish/files/{{ item }}"
    dest: "~/.config/fish/{{ item }}"
    force: yes
  loop:
    - config.fish
    - functions
    - conf.d

- name: Get Homebrew prefix path
  shell: brew --prefix
  changed_when: false
  register: brew_prefix
  check_mode: false

- name: Add fish to /etc/shells
  lineinfile:
    path: /etc/shells
    line: "{{ brew_prefix.stdout }}/bin/fish"
    regexp: "^{{ brew_prefix.stdout }}/bin/fish$"
  become: true
  become_method: sudo

- name: Install fish-async-prompt
  shell:
    cmd: fisher install acomagu/fish-async-prompt
    creates: "~/.config/fish/conf.d/__async_prompt.fish"
    executable: "{{ brew_prefix.stdout }}/bin/fish"

- name: Install fzf.fish
  shell:
    cmd: fisher install PatrickF1/fzf.fish
    creates: "~/.config/fish/conf.d/fzf.fish"
    executable: "{{ brew_prefix.stdout }}/bin/fish"

- name: Install Puffer Fish
  shell:
    cmd: fisher install nickeb96/puffer-fish
    creates: "~/.config/fish/conf.d/puffer_fish_key_bindings.fish"
    executable: "{{ brew_prefix.stdout }}/bin/fish"

- name: Install done
  shell:
    cmd: fisher install franciscolourenco/done
    creates: "~/.config/fish/conf.d/done.fish"
    executable: "{{ brew_prefix.stdout }}/bin/fish"
