---

- name: Install fish
  community.general.homebrew:
    name:
      - fish
      - fisher

- name: Link fish dotfiles
  file:
    state: link
    src: "../../{{ playbook_dir | replace(lookup('env', 'HOME') + '/', '') }}/roles/fish/files/{{ item }}"
    dest: "~/.config/fish/{{ item }}"
    force: yes
  loop:
    - config.fish
    - functions
    - conf.d

- name: Get Homebrew prefix path
  shell: brew --prefix
  changed_when: false
  register: brew_prefix
  check_mode: false

- name: Add fish to /etc/shells
  lineinfile:
    path: /etc/shells
    line: "{{ brew_prefix.stdout }}/bin/fish"
    regexp: "^{{ brew_prefix.stdout }}/bin/fish$"
  become: true
  become_method: sudo
