---

- name: Install bash 5 via Homebrew
  community.general.homebrew:
    name: bash
  register: bash_install

- name: Link bash
  community.general.homebrew:
    name: bash
    state: linked
  when: bash_install.changed

- name: Link bash dotfiles
  file:
    state: link
    src: "{{ playbook_dir | replace(lookup('env', 'HOME') + '/', '') }}/roles/bash/files/{{ item }}"
    dest: "~/.{{ item }}"
    force: yes
  loop:
    - bash_colors
    - bash_profile
    - bash_prompt
    - inputrc

- name: Link bin and dotoverrides
  file:
    state: link
    src: "{{ playbook_dir | replace(lookup('env', 'HOME') + '/', '') }}/{{ item }}"
    dest: "~/.{{ item }}"
    force: yes
  loop:
    - bin
    - dotoverrides

- name: Create cache folder
  file:
    state: directory
    dest: ~/Library/Caches/org.freedesktop

- name: Get Homebrew prefix path
  shell: PATH="/opt/homebrew/bin:$PATH" brew --prefix
  changed_when: False
  register: brew_prefix
  check_mode: no

- name: Add bash to /etc/shells
  lineinfile:
    path: /etc/shells
    line: "{{ brew_prefix.stdout }}/bin/bash"
    regexp: "^{{ brew_prefix.stdout }}/bin/bash$"
  become: yes
  become_method: sudo

- name: Set shell for user
  user:
    name: "{{ ansible_user_id }}"
    shell: "{{ brew_prefix.stdout }}/bin/bash"
  become: yes
  become_method: sudo
