---

- hosts: 127.0.0.1
  connection: local
  vars:
    homebrew_taps: []
    homebrew_use_brewfile: false
  roles:
    - geerlingguy.mac.homebrew
    - bash
    - git
    - ssh
    - vim
    - tmux
    - packages
    - profile
