---
- name: Activate Settings
  ansible.builtin.command: /System/Library/PrivateFrameworks/SystemAdministration.framework/Resources/activateSettings -u
  changed_when: true

- name: Kill Dock
  ansible.builtin.command: killall Dock
  changed_when: true

- name: Kill SystemUIServer
  ansible.builtin.command: killall SystemUIServer
  changed_when: true

- name: Restart Finder
  ansible.builtin.command: killall Finder
  changed_when: true

- name: Restart usernoted
  ansible.builtin.command: killall usernoted
  changed_when: true
