---

- name: Add cross compiler tap
  homebrew_tap:
    name: osx-cross/avr

- community.general.homebrew:
    name:
      - osx-cross/avr/avr-binutils
      - osx-cross/avr/avr-gcc

- community.general.homebrew_cask:
    name:
      - arduino
      - teensy
    install_options: 'appdir=~/Applications'
