---

- community.general.homebrew:
    name:
      - black
      - flake8
      - isort
      - pipenv
      - python
      - python-setuptools
      - virtualenvwrapper

- name: Link flake8 config
  file:
    state: link
    src: "../{{ playbook_dir | replace(lookup('env', 'HOME') + '/', '') }}/roles/packages/files/dev/flake8"
    dest: ~/.config/flake8
    force: yes
