---

- name: Get Homebrew prefix path
  shell: brew --prefix
  changed_when: False
  register: brew_prefix
  check_mode: no

- community.general.homebrew:
    name:
      - python
      - python@3.7

- pip:
    name:
      - black
      - isort
      - flake8
      - pep8-naming
      - pipenv
      - virtualenvwrapper
    extra_args: --user
    executable: "{{ brew_prefix.stdout }}/bin/pip3"

- name: Link flake8 config
  file:
    state: link
    src: "../{{ playbook_dir | replace(lookup('env', 'HOME') + '/', '') }}/roles/packages/files/dev/flake8"
    dest: ~/.config/flake8
    force: yes
