---

- homebrew:
    name:
      - python

- pip:
    name:
      - flake8
      - pep8-naming
      - pipenv
      - virtualenvwrapper
    extra_args: --user
    executable: pip3

- name: Link flake8 config
  file:
    state: link
    src: "../{{ playbook_dir | replace(lookup('env', 'HOME') + '/', '') }}/roles/path/files/dev/flake8"
    dest: ~/.config/flake8
    force: yes
