---
# Modifier mappings are stored per keyboard, thus need to get its product and
# vendor ID.
# Internal keyboard is always made by Apple, thus vendor ID is the same, no
# need to fetch it, it is always 1452
- name: Get keyboard product id
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      ioreg -a -l | \
      xpath -q -e '(//*[string[text()="Apple Internal Keyboard / Trackpad"]]/key[text() = "ProductID"]/following-sibling::integer[1]/text())[1]'
    executable: /bin/bash
  changed_when: false
  check_mode: false
  register: keyboard_productid

# Need to check the value beforehand as for this to work properly the format
# stored is not the same as the format written
- name: Check caps lock mapping to escape
  community.general.osx_defaults:
    host: currentHost
    key: com.apple.keyboard.modifiermapping.1452-{{ keyboard_productid.stdout }}-0
    type: array
    value:
      - "{"
      - HIDKeyboardModifierMappingDst = 30064771113;
      - HIDKeyboardModifierMappingSrc = 30064771129;
      - "}"
  check_mode: true
  register: capslock_mapping

# To properly set the mapping we need to write the value in xml format otherwise
# the mappings will be stored as strings and activating will throw an error
- name: Map caps lock to escape # noqa: no-handler
  community.general.osx_defaults:
    host: currentHost
    key: com.apple.keyboard.modifiermapping.1452-{{ keyboard_productid.stdout }}-0
    type: array
    value:
      - <dict><key>HIDKeyboardModifierMappingDst</key><integer>30064771113</integer><key>HIDKeyboardModifierMappingSrc</key><integer>30064771129</integer></dict>
  notify: Activate Settings
  when: capslock_mapping.changed

- name: Enable accent menu on long press
  community.general.osx_defaults:
    key: ApplePressAndHoldEnabled
    type: bool
    value: true

- name: Disable automatic spelling correction
  community.general.osx_defaults:
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false
  notify: Activate Settings

- name: Disable automatic capitalization
  community.general.osx_defaults:
    key: NSAutomaticCapitalizationEnabled
    type: bool
    value: false
  notify: Activate Settings

- name: Disable adding full stop with double-space
  community.general.osx_defaults:
    key: NSAutomaticPeriodSubstitutionEnabled
    type: bool
    value: false
  notify: Activate Settings

- name: Disable smart quotes
  community.general.osx_defaults:
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: false
  notify: Activate Settings

- name: Disable smart dashes
  community.general.osx_defaults:
    key: NSAutomaticDashSubstitutionEnabled
    type: bool
    value: false
  notify: Activate Settings

- name: Enable keyboard navigation in modals
  community.general.osx_defaults:
    key: AppleKeyboardUIMode
    type: int
    value: 3
  notify: Activate Settings

- name: Show emoji picker with FN key
  community.general.osx_defaults:
    domain: com.apple.HIToolbox
    key: AppleFnUsageType
    type: int
    value: 2
  notify: Activate Settings
