---
- ansible.builtin.import_tasks: keyboard.yml
- ansible.builtin.import_tasks: trackpad.yml
- ansible.builtin.import_tasks: dock.yml
- ansible.builtin.import_tasks: screensaver.yml
- ansible.builtin.import_tasks: controlcentre.yml
- ansible.builtin.import_tasks: finder.yml
- ansible.builtin.import_tasks: terminal.yml
- ansible.builtin.import_tasks: misc.yml
- ansible.builtin.import_tasks: firewall.yml
  become: true
