---
- name: Disable screenshot shadow
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: disable-shadow
    type: bool
    value: true

- name: Disable personalized advertising
  community.general.osx_defaults:
    domain: com.apple.AdLib
    key: allowApplePersonalizedAdvertising
    type: bool
    value: false

- name: Disable the “Are you sure you want to open this application?” dialog
  community.general.osx_defaults:
    domain: com.apple.LaunchServices
    key: LSQuarantine
    type: bool
    value: false

- name: Play feedback when volume is changed
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.sound.beep.feedback
    type: integer
    value: 1

- name: Only show notification previews when unlocked
  community.general.osx_defaults:
    domain: com.apple.ncprefs
    key: content_visibility
    type: integer
    value: 2
  notify: Restart usernoted
