---

- name: Install git via Homebrew
  community.general.homebrew:
    name: git

- name: Link config files and folders
  file:
    state: link
    src: "{{ playbook_dir | replace(lookup('env', 'HOME') + '/', '') }}/roles/git/files/{{ item }}"
    dest: "~/.{{ item }}"
    force: yes
  loop:
    - git_template
    - gitconfig
    - githelpers
    - gitignore_global
    - gitattributes_global
