---

- name: Check Homebrew
  stat:
    path: /usr/local/bin/brew
  register: brew_exists

- name: Install Homebrew
  shell: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: brew_exists.stat.exists == false
