---

- name: Install fzf via Homebrew
  community.general.homebrew:
    name: fzf
  register: fzf_package

- name: Run fzf install script
  shell: "{{ brew_prefix }}/opt/fzf/install --no-key-bindings --completion --no-update-rc"
  when: fzf_package.changed
