---

- name: Install fzf via Homebrew
  community.general.homebrew:
    name: fzf
  register: fzf_package

- name: Get Homebrew prefix path
  shell: brew --prefix
  changed_when: False
  register: brew_prefix
  check_mode: no
  when: fzf_package.changed

- name: Run fzf install script
  shell: "{{ brew_prefix.stdout }}/opt/fzf/install --no-key-bindings --completion --no-update-rc"
  when: fzf_package.changed
