---

- name: Install tmux via Homebrew
  community.general.homebrew:
    name:
      - reattach-to-user-namespace
      - tmux

- name: Link config files and folders
  file:
    state: link
    src: "{{ playbook_dir | replace(lookup('env', 'HOME') + '/', '') }}/roles/tmux/files/{{ item }}"
    dest: "~/.{{ item }}"
    force: yes
  loop:
    - tmux-linux.conf
    - tmux-osx.conf
    - tmux.conf

- name: Clone TPM
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    depth: 1
    version: v3.0.0
  register: tpm

- name: Install tmux plugins
  shell: ~/.tmux/plugins/tpm/bin/install_plugins
  when: tpm.changed
