#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="$(git rev-parse --git-dir)"
trap 'rm -f "$dir/$$.tags"' EXIT

git ls-files | \
  ctags --tag-relative -L - -f"$dir/$$.tags" --languages=-javascript,sql

if [ "${VIRTUAL_ENV}" ] && [ -d "${VIRTUAL_ENV}" ]; then
  PYTHON_LIBS="$(python -c 'import os,sys;print(os.path.realpath(sys.argv[1]))' "$(which python)" | sed -e 's/bin/lib/')"
  SITE_DIR="$(python -m site | grep "${VIRTUAL_ENV}" | grep "[0-9]',$" | sed -e "s/^\s*'\(.*\)',$/\1/")"
  ctags --append -f "$dir/$$.tags" --tag-relative "${SITE_DIR}" "$PYTHON_LIBS"
fi
mv "$dir/$$.tags" "$dir/tags"
