---

- community.general.homebrew_cask:
    name:
      - aerial
      - appcleaner
      - bettertouchtool
      - disk-inventory-x
      - itsycal
      - keepingyouawake
      - spectacle
    install_options: 'appdir=~/Applications'
