#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | \
  ctags --tag-relative -L - -f"$dir/$$.tags" --languages=-javascript,sql
if [ $VIRTUAL_ENV -a -d $VIRTUAL_ENV ]; then
  PYTHON_LIBS="$(python -c 'import os,sys;print os.path.realpath(sys.argv[1])' $(which python) | sed -e 's/bin/lib/')"
  ctags --append -f "$dir/$$.tags" --tag-relative "$VIRTUAL_ENV/lib/python2.7/site-packages" "$PYTHON_LIBS"
fi
mv "$dir/$$.tags" "$dir/tags"
